
[colors]
; Backgrounds
background = #1e222a           ; nvim bg
background-alt = #282c34       ; real OneDark bg
background-light = #353b45     ; one_bg2
background-lighter = #373b43   ; one_bg3

; Text
foreground = #abb2bf           ; white
foreground-dim = #6f737b       ; light_grey
foreground-disabled = #565c64  ; grey_fg

; Accents
primary = #61afef              ; blue (also pmenu_bg)
secondary = #98c379            ; green
alert = #e06c75               ; red
warning = #e7c787             ; yellow
highlight = #81A1C1           ; nord_blue

; Special
line = #31353d                ; vertsplit line
statusline = #22262e          ; statusline_bg
folder = #61afef              ; folder_bg
disabled = #6c7086
