
# Font
font_family FiraCode Nerd Font Mono Regular
bold_font FiraCode Nerd Font Mono Bold
italic_font FiraCode Nerd Font Mono Light
bold_italic_font FiraCode Nerd Font Mono Medium
font_size 12.0
disable_ligatures never

# Colors
foreground #abb2bf
background #1e222a
selection_foreground #1e222a
selection_background #abb2bf

# Black
color0 #1b1f27
color8 #42464e

# Red
color1 #e06c75
color9 #DE8C92

# Green
color2 #98c379
color10 #7eca9c

# Yellow
color3 #e7c787
color11 #EBCB8B

# Blue
color4 #61afef
color12 #81A1C1

# Magenta
color5 #de98fd
color13 #c882e7

# Cyan
color6 #a3b8ef
color14 #519ABA

# White
color7 #abb2bf
color15 #ffffff

# Cursor
cursor #abb2bf
cursor_text_color #1e222a

# Tabs
active_tab_foreground #1e222a
active_tab_background #61afef
inactive_tab_foreground #abb2bf
inactive_tab_background #2d3139

# Window
active_border_color #61afef
inactive_border_color #31353d

# URL
url_color #61afef

# Marks
mark1_foreground #1e222a
mark1_background #e06c75
mark2_foreground #1e222a
mark2_background #98c379
mark3_foreground #1e222a
mark3_background #e7c787
